### ISSUE TITLE
Timeouts?

### ISSUE THREAD

**Issue by norru** [lambdastackio/aws-sdk-rust#1]
Hi,

I am porting over some code from another project and I need to set the S3 Client upload code's up timeout.

I could not find an API to set the client's timeout. What's the default?

I need to distribute the project with no source dependencies to minimize handover complexity (but cargo.io is fine) so forking is a no-no unless I fork, rename and upload to cargo as a different project.

Cheers
Nico

**Comment by hanscj1** [comment]
The lower level timeouts are part of hyper. Most likely we will change to a futures based version soon and maybe replace hyper or have a different feature option.
