### ISSUE TITLE
aws-sdk-rust 0.1.41 is broken because of xml-rs

### ISSUE THREAD

**Issue by klingtnet** [lambdastackio/aws-sdk-rust#11]
aws-sdk-rust in version 0.1.41 does not compile for 

```sh
$ rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)
$ cargo build
...
error: no rules expected the token `flags`
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.1.26/src/writer/emitter.rs:115:5
    |
115 |     flags IndentFlags: u8 {
    |     ^^^^^

error: Could not compile `xml-rs`.
```

Updating `xml-rs` to a more recent version, i.e. `>=0.2` with the newest one being `0.6` at the moment, breaks the implementation.

Optional: You should think about setting up some CI runner to see if builds are broken with recent Rust versions. There is good documentation about how to setup such a continuous integration runner, e.g. [here](https://github.com/japaric/trust) and [here](https://docs.travis-ci.com/user/languages/rust/).

**Comment by hanscj1** [comment]
Agree on CI!! Will take a look.

**Comment by hanscj1** [comment]
Upgraded xml-rs and tested with latest rust. Ran through s3 examples. New version is on crates.io and here. Closing issue. thx

**Comment by klingtnet** [comment]
Thanks for fixing this that quickly!

**Comment by hanscj1** [comment]
NP.
