### ISSUE TITLE
OpenSSL versions, MSVC build not supported

### ISSUE THREAD

**Issue by norru** [lambdastackio/aws-sdk-rust#2]
I am trying a windows build on MSVC 2013 against the precompiled OpenSSL 1.1.0 as suggested by the rust-openssl docs.

This doesn't appear to be supported by openssl:0.7.17 but it is supported in openssl:0.9.1.

Would you mind upgrading?

**Comment by hanscj1** [comment]
I see what you're saying. Hyper is the http library we use and uses .7. You can clone hyper, change the version in Cargo.toml and change the reference in aws-sdk-rust Cargo.toml to see if that works for you.

**Comment by hanscj1** [comment]
I meant that hyper is using openssl .7x

**Comment by norru** [comment]
Yes, that is the problem.

**Comment by hanscj1** [comment]
I sometimes test or make mods to hyper for testing purposes. I usually just git clone hyper and then create a .cargo/config in the root of the aws-sdk-rust directory and add the following line to it:
paths = ["<whatever the path is to the git clone hyper>/hyper"]

Then it uses that version of hyper when I compile aws-sdk-rust. You can then change the Cargo.toml in hyper to the new version of openssl to see if it works for you. thx

**Comment by hanscj1** [comment]
Latest version of hyper and openssl has been updated. Thanks
